# docker compose to run the dev/builder.Dockerfile
version: '3.7'
services:
  builder:
    security_opt:
      - seccomp:dev/chrome.json
    build:
      context: .
      dockerfile: dev/builder.Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - .:/app
      - ./serviceAccountKey.json:/usr/src/app/data/serviceAccountKey.json
