# docker compose to run the dev/builder.Dockerfile
version: '3.7'
services:
  builder:
    security_opt:
      - seccomp:dev/chrome.json
    build:
      context: .
      dockerfile: dev/builder.Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - SUPABASE_URL=http://192.168.1.134:54321
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    volumes:
      - .:/app