services:
  BulletinBoard.infrastructure.WhatsappMessageRepositoryConfig:
    factory:
      class: '../../../../Contexts/BulletinBoard/infrastructure/whatsapp/WhatsappMessageRepositoryConfigFactory'
      method: 'createConfig'
  Notifications.domain.MessagesRepository:
    class: ../../../../Contexts/BulletinBoard/infrastructure/whatsapp/WhatsappMessageRepository.ts
    arguments: ['@Shared.domain.EventBus', '@BulletinBoard.infrastructure.WhatsappMessageRepositoryConfig']
  Notifications.application.FetchAndPublishNewNotices:
    class: ../../../../Contexts/BulletinBoard/application/FetchAndPublishNewNotices.ts
    arguments: ['@Notifications.domain.MessagesRepository']
  BulletinBoard.application.CreateNotice:
    class: ../../../../Contexts/BulletinBoard/application/Create/CreateNotice.ts
    arguments: []

  BulletinBoard.application.CreateANoticeOnMessageReceived:
    class: ../../../../Contexts/BulletinBoard/application/Create/CreateANoticeOnMessageReceived.ts
    arguments: ['@BulletinBoard.application.CreateNotice']
    tags:
      - { name: 'domainEventSubscriber' }
