services:
  BulletinBoard.infrastructure.WhatsappMessageRepositoryConfig:
    factory:
      class: '../../../../Contexts/BulletinBoard/infrastructure/whatsapp/WhatsappMessageRepositoryConfigFactory'
      method: 'createConfig'
  BulletinBoard.domain.MessagesRepository:
    class: ../../../../Contexts/BulletinBoard/infrastructure/whatsapp/WhatsappMessageRepository
    arguments: ['@Shared.domain.EventBus', '@BulletinBoard.infrastructure.WhatsappMessageRepositoryConfig']
  BulletinBoard.application.FetchAndPublishNewNotices:
    class: ../../../../Contexts/BulletinBoard/application/FetchAndPublishNewNotices
    arguments: ['@BulletinBoard.domain.MessagesRepository']
  BulletinBoard.infrastructure.NoticesRepository:
    class: ../../../../Contexts/BulletinBoard/infrastructure/supabase/SupabaseNoticeRepository
    arguments: ['@Shared.infrastructure.SupabaseRepositoryConfig']
  BulletinBoard.application.CreateNotice:
    class: ../../../../Contexts/BulletinBoard/application/Create/CreateNotice
    arguments: ['@BulletinBoard.infrastructure.NoticesRepository', '@Shared.domain.EventBus']
  BulletinBoard.application.CreatePastNotice:
    class: ../../../../Contexts/BulletinBoard/application/Create/CreatePastNotice
    arguments: ['@BulletinBoard.infrastructure.NoticesRepository', '@Shared.domain.EventBus']

  BulletinBoard.application.CreateAPastNoticeOnMessageFetched:
    class: ../../../../Contexts/BulletinBoard/application/Create/CreateAPastNoticeOnMessageFetched
    arguments: ['@BulletinBoard.application.CreatePastNotice']
    tags:
      - { name: 'domainEventSubscriber' }
  BulletinBoard.application.CreateANoticeOnMessageReceived:
    class: ../../../../Contexts/BulletinBoard/application/Create/CreateANoticeOnMessageReceived
    arguments: ['@BulletinBoard.application.CreateNotice']
    tags:
      - { name: 'domainEventSubscriber' }
  BulletinBoard.application.LogCreatedNotice:
    class: ../../../../Contexts/BulletinBoard/application/LogCreateNotice/LogNoticeOnNoticeCreated
    tags:
      - { name: 'domainEventSubscriber' }
